# Site settings
title: Walter Carvalho
highlighter: pygments
email: waltervascarvalho@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Walter Carvalho, JavaScript Developer. London.
url: "http://waltfy.net" # the base hostname & protocol for your site
twitter_username: waltfy
github_username:  waltfy
assets: /assets
# Build settings
markdown: kramdown
